---
version: '3'
services:
  mysql:
    image: 'mariadb'
    restart: 'unless-stopped'
    volumes:
      - 'mysql_db:/var/lib/mysql'
    ports:
      - '3306:3306'
      - '33060:33060'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
volumes:
  mysql_db:
